# Generated by Django 6.0.7 on 2026-07-13 17:07

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_slug_alter_faultreport_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to=articles.models.article_cover_directory_path, verbose_name='Cover image'),
        ),
    ]
