# Generated by Django 6.0.7 on 2026-07-18 12:16

import datetime
from django.db import migrations, models


def backfill_published_date(apps, schema_editor):
    Article = apps.get_model('articles', 'Article')
    for article in Article.objects.all():
        Article.objects.filter(pk=article.pk).update(published_date=article.created_date.date())


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date', '-id'], 'permissions': (('svjis_view_redaction_menu', 'Can view Redaction menu'), ('svjis_edit_article', 'Can edit Article'))},
        ),
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Publish date'),
        ),
        migrations.RunPython(backfill_published_date, migrations.RunPython.noop),
    ]
